### ISSUE TITLE
Error while installing binary: Checksum rejected

### ISSUE THREAD

**Issue by michelneufeglise** [pact-foundation/pact-js-core#282]
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: _e.g. Mac OSX Catalina 10.15.5
- **Consumer Pact library**:   "@pact-foundation/pact": "^9.15.5",
- **Node Version**: `v14.15.4`

### Issue Checklist

Please confirm the following:

- [ x] I have upgraded to the latest
- [ x] I have the read the FAQs in the Readme
- [ x] I have triple checked, that there are **no unhandled promises** in my code
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

the pact_binary_location is set to company specifik location and download from there works fine !

### Actual behaviour

Checksum error when installing binary on both OSX and Linux build servers 

Error while installing binary: Checksum rejected for file 'pact-1.88.49-osx.tar.gz' with checksum pact-1.88.49-osx.tar.gz.checksum
### Steps to reproduce

_How can someone else reproduce this bug?_ Change the pact_binary_location for all 9.* versions 

_For extra bonus points and internet karma, provide a repository, gist or reproducible code snippet so that we can test the problem._

_We recommend forking the project and modifying a relevant example [in the examples folder](https://github.com/pact-foundation/pact-js/blob/master/examples)_

### Relevant log files

_Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link to a gist)._

**Comment by michelneufeglise** [comment]
Hi Matt and Timothy,

Changing it to a local binary pact location worked fine, no problems with the checksums so it seems the problem is related to the git location of my company where it is stored, i am switching to a different location ( nexus ) for the binaries now to see if that does the trick but i think it will work. Will keep you updated about the results !

**Comment by mefellows** [comment]
Thanks Michel.

One hypothesis I have is that proxy settings might be getting in the way. i.e. when the system attempts to download the binary from your hosted git URL, it is passing through a proxy that is presenting an auth challenge (or similar). When the file is downloaded, it's not actually a zip file but most likely an HTML document. 

I think we could add some more debugging into the package that enables trace logging, and we could print out what is happening. 

What do you think Tim?

**Comment by TimothyJones** [comment]
So, while working on the (unrelated) FFI branch, I noticed that 404s during the download incorrectly result in a successful download that contains the 404 error instead of the binary. I think the error handling isn't quite right.

Could that be what is happening here? Have you tried opening the download up to see whether the file is the archive it is supposed to be?

**Comment by mefellows** [comment]
That certainly lends credence to the theory.

Doing it via a browser is not going to be the best debugging approach however, because likely any auth session would still be valid. When pact-node tries to download it, any credentials are unlikely to be passed along (because we don't have any mechanism to do so, outside of standard `http_proxy` and `https_proxy`), so that could be it.

**Comment by michelneufeglise** [comment]
Hi Matt and Timothy,

I am trying a really simple solution now, just added the four different os binaries to the same project which needs them, so it gets a relative local path. That works fine locally but off course that is to be expected, but I think it should also work fine on the build servers because there are no proxies in between anymore, again I will keep you updated !

**Comment by rlagu** [comment]
I am having same issue. Getting error while downloading nexus 

![image](https://user-images.githubusercontent.com/63467730/130661024-247dec95-1322-4402-b9bd-1238413bca45.png)

working fine with local path

![image](https://user-images.githubusercontent.com/63467730/130661273-45183417-d0cd-4432-8e64-ca3710fb302c.png)

**Comment by TimothyJones** [comment]
We’re working on a permanent fix for this, by bundling the binaries with the package. 

In the meantime, try opening the file in a text editor- usually it’s an error message from github or a proxy you have set up.

Also, if you’re able to try the beta release, I believe the most recent version has the binaries bundled with it. However, the release is not stable yet, so it might not suit your needs

**Comment by BrendonReed** [comment]
Hi, I experienced a similar issue, so just jumping in here to add what I found.

The issue for me was definitely the proxy -- I tracked it down to the switch from requests to needle for doing the download. I then replicated with a simple request vs needle file download. My corporate proxy worked fine with Request, but not with Needle. My guess is that it has to do with http vs https, something like the proxy is plain http even for https. Probably not an uncommon scenario for a corporate proxy. 

If you're bundling the binaries then I suppose that would solve my issue as well, but I'm not sure of the timeline. Because most people don't use pact-js-core directly, is it simple to provide me a link to an issue or something that's tracking so I can get a better picture of when it might be available to me?

**Comment by mefellows** [comment]
The latest version of Pact JS (beta) bundles its dependency directly (https://github.com/pact-foundation/pact-js/#pact-js-v3), and better yet, it doesn't use Ruby under the hood (so no concerns around executable permissions on locked down corporate machines).

This [project](https://github.com/pact-foundation/pact-js/projects/3) tracks the project of the work. You can see the MVP line for the next major release there - things are moving, but the interface is likely to change.

To solve the immediate problem, it seems that Needle does not support this (see https://github.com/tomas/needle/issues/336). It's possible we can detect the presence of the standard environment variables and then configure Needle on the fly. More preferably, we just bundle the dependency.

@BrendonReed IIRC you were also wanting to configure the location of the pre-downloaded artifacts. If that's still the case, please raise an issue and/or PR, we'd happily accept that if the beta release is not suitable for you.

**Comment by mefellows** [comment]
Closing as we have removed the install-time download from the latest.
