### ISSUE TITLE
windows(LoadError): Cannot load such  file

### ISSUE THREAD

**Issue by Yashwanthhs** [pact-foundation/pact-js-core#307]
_Thank you for reporting a bug! We appreciate it very much. Issues are a big input into the priorities for Pact development_

_All italic text in this template is safe to remove before submitting_

_Thanks again!_

### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: Windows
- **Pact Node version**: Pact v9.11.1 Node v14.4_
- **Node Version**: 14.4
- **Other Versions**: _Any other versions you think might be relevant (optional)_

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour
Provider Test cases should run

### Actual behaviour

Provider Test cases Fails with **LoadError**

### Steps to reproduce

Followed the steps by enabling long path in registry as [given  here](https://github.com/pact-foundation/pact-js-core/blob/master/README.md#enable-long-paths)
Didn't Help

### Relevant log files

node_modules/@pact-foundation/pact-node/standalone/win32-1.88.49/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/app.rb:3:in `require': cannot load such file -- pact/provider_verifier/provider_states/add_provider_states_header (LoadError)

**Comment by mefellows** [comment]
It looks like the long path issue though. Have you tried reducing the length of the project directory?

Also consider using the v3 beta release documented in the readme

**Comment by TimothyJones** [comment]
As far as I understand, the long path limit in windows was removed in windows 10 (so the registry fix doesn't make a difference, because it's already implied to be enabled). However, as I understand it, Ruby still has a limit -even in the latest version.

For now the workarounds that Matt suggested are your options - reducing the length of the path that the project is running from, or using the v3 pact parts of the upcoming beta.

I'll leave this issue open because it does indicate that we need to update the documentation.

**Comment by mefellows** [comment]
Closing as per the other windows issues. The latest version uses the new rust core which doesn't have this issue.
