### ISSUE TITLE
Set PACT_DO_NOT_TRACK by default

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-js-core#360]
### Checklist

- [X] [Searched the issues to check that this feature hasn't been requested before](https://github.com/pact-foundation/pact-js-core/issues?q=is%3Aissue)
- [X] Checked the documentation to see if it is possible to do what I want already 

### Feature description

Set PACT_DO_NOT_TRACK by default, and update the message to suggest that people can un-set it.

### Use case

As mentioned in the discussion here: https://github.com/pact-foundation/pact-js-core/pull/359

> I think it's already pretty questionable that our tracking message is essentially "we just tracked you! you can disable this for next time if you want". That's not how consent for tracking should work.

In addition to this not being nice behaviour for users, I think it also contravenes the GDPR, which is explicit that anything that could be used in the process of identifying users must be opt-in, not opt-out.

**Comment by mefellows** [comment]
See https://github.com/pact-foundation/pact-js-core/pull/359#issuecomment-1027529629 and also a related (resolved) [complaint](https://github.com/pact-foundation/pact-js/issues/272) from when we first introduced analytics a few years back.

In short, I don't think we need to reverse this default.

**Comment by TimothyJones** [comment]
I think it's worth revisiting that decision if we merge the additional tracking. I think we should either:

* Change the default to opt-in if we merge the additional tracking
* Not merge the additional tracking

**Comment by YOU54F** [comment]
I appreciate some of the concerns and the raising of this issue, and support both sides of the fence (I set tracking off on my machines, but am okay with being tracked - its part of our modern life, love it or hate it), however our guidance is clear and consistent on the matter, and in line with other tools. I am going to close this topic and allow for centralised discussions by way on an RFC. 

Tracking guidance is provided here

https://docs.pact.io/telemetry

All implementations support `PACT_DO_NOT_TRACK` and all test runs will inform the user of this providing them the option to opt-out.

This is the same process used by many everyday commonly used tools by developers

- https://docs.brew.sh/Analytics#opting-out
- https://learn.microsoft.com/en-us/dotnet/core/tools/telemetry#how-to-opt-out
- Pacts opt out (both main docs and js repos)
  - https://docs.pact.io/telemetry#opt-out
  - https://github.com/pact-foundation/pact-js-core?tab=readme-ov-file#do-not-track
  - https://github.com/pact-foundation/pact-js?tab=readme-ov-file#do-not-track
  - https://github.com/pact-foundation/pact-js-cli?tab=readme-ov-file#do-not-track

If anyone else highly objects, please feel free to raise an [RFC](https://github.com/pact-foundation/roadmap/issues/new/choose) over in our [roadmap](https://github.com/pact-foundation/roadmap) repo, the process is laid out [here](https://github.com/pact-foundation/roadmap/blob/master/rfc/0000-rfc-process.md) for consideration.

We do want to know how our tools are being used, in order to spend the limited time we have as maintainers, serving the tools in the community that are used the most.
