### ISSUE TITLE
Automatically taking the details of request body and expected response body if it changed 

### ISSUE THREAD

**Issue by akanksha-centric** [pact-foundation/pact-js-core#361]
Hi 

Suppose I have created thousand of pacts and for that we have created thousand of Request body and expected Response body for a consumer.
So main problem here is maintaining these request and response body  generally have lots of static data which may be changed during development and after that if we run contract testing the test will failed so is there are any solution to sync automatically contract test request and expected response body with real time provider.
or can you provide this kind of tool to sync automatically.

**Comment by mefellows** [comment]
Hi Akanksha, 

> So main problem here is maintaining these request and response body generally have lots of static data which may be changed during development and after that if we run contract testing the test will failed

Without further detail, this sounds to me like perhaps you're matching too strictly. I'd take a look at the consumer test guidance page here for best practices / tips on making them more robust: https://docs.pact.io/consumer#choose-the-right-type-of-matching-for-the-situation

If the provider test was able to pass at some point and stopped working, that would also give me pause to understand the kind of workflow you have created that could lead to such mismatches occurring with such regularity.

> or can you provide this kind of tool to sync automatically.

Could you perhaps describe what you're wanting the sync to be? Essentially, the provider states are the keys to communicating data needs (there are also "injected provider states" in the latest v3 Pact JS that make this even better). How would syncing the data not prevent an equally difficult situation of having to align things?

You may also appreciate this [thread](https://pact-foundation.slack.com/archives/C5F4KFKR8/p1643294644093300) in slack. 

For now, I'm going to close this because it's a framework level change that would need to be enacted to achieve this, but I think a good conversation in slack with more detail would be useful and we can generate any feature requests as a result of it.
